name: K8s Cluster Setup & Deploy Istio Stach CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-k8s-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl tar
          # Install Docker (if not preinstalled)
          if ! command -v docker &> /dev/null; then
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
          fi
          # Install Kind
          if ! command -v kind &> /dev/null; then
            curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
            chmod +x ./kind
            sudo mv ./kind /usr/local/bin/kind
          fi
          # Install kubectl
          if ! command -v kubectl &> /dev/null; then
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
          fi

      - name: Run K8s Cluster Setup Script
        run: |
          chmod +x ./bin/setup-k8s-cluster.sh
          ./bin/setup-k8s-cluster.sh

      - name: Wait for 30 seconds
        run: sleep 30

      - name: Check all Pods are Ready
        run: |
            kubectl get pods --all-namespaces
            NOT_READY=$(kubectl get pods --all-namespaces --field-selector=status.phase!=Running | wc -l)
            if [ "$NOT_READY" -gt 0 ]; then
                echo "Error: Some pods are not ready!"
                exit 1
            fi
            echo "All pods are running."            

      - name: Download istioctl and Install Istio CRDs
        run: |
            ISTIO_VERSION=1.28.2
            curl -L https://istio.io/downloadIstio | ISTIO_VERSION=$ISTIO_VERSION sh -
            export PATH=$PWD/istio-$ISTIO_VERSION/bin:$PATH
            istioctl version
            bash scenarios/00-prerequisites/install-istio-crds.sh
            bash scenarios/00-prerequisites/validate-istio-crds.sh

      - name: Install Gateway CRDs and Validate Gateway CRDs
        run: |
          bash scenarios/00-prerequisites/install-gateway-api-crds.sh
          bash scenarios/00-prerequisites/validate-gateway-api-crds.sh

      - name: Setup Base Bookinfo 
        run: |
            kubectl apply -f scenarios/01-base-bookinfo/namespace.yaml
            kubectl apply -f scenarios/01-base-bookinfo/details.yaml 
            kubectl apply -f scenarios/01-base-bookinfo/productpage.yaml 
            kubectl apply -f scenarios/01-base-bookinfo/ratings.yaml 
            kubectl apply -f scenarios/01-base-bookinfo/reviews.yaml 

      - name: Wait for 30 seconds and Then Validate base bookinfo setup
        run: |
            sleep 30
            kubectl get pods -n bookinfo-base -l scenario=01-base-bookinfo
            kubectl get svc -n bookinfo-base -l scenario=01-base-bookinfo

      - name: Delete All Resource in Scenario 01 and Validate 
        run: |
          kubectl delete namespace bookinfo-base 
          kubectl get all -n bookinfo-base 

      - name: Shutdown K8s Cluster
        run: |
          chmod +x ./bin/shutdown-k8s-cluster.sh
          ./bin/shutdown-k8s-cluster.sh
