name: K8s Cluster Setup & Deploy Istio Stach CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-k8s-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl tar
          # Install Docker (if not preinstalled)
          if ! command -v docker &> /dev/null; then
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
          fi
          # Install Kind
          if ! command -v kind &> /dev/null; then
            curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
            chmod +x ./kind
            sudo mv ./kind /usr/local/bin/kind
          fi
          # Install kubectl
          if ! command -v kubectl &> /dev/null; then
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
          fi

      - name: 01 - Create K8s Cluster
        run: |         
          bash ./bin/01-k8s-cluster.sh

      - name: 02 - Create Namespaces
        run: |         
          bash ./bin/02-namespaces.sh

      - name: 03 - Add Helm Repos
        run: |          
          bash ./bin/03-helm-repos.sh

      - name: 04 - Install Observability Stack
        run: |
          bash ./bin/04-observability.sh

      - name: 05 - Install Istio
        run: |
          bash ./bin/05-istio.sh
          # validate all istio crds 
          bash scenarios/00-prerequisites/validate-istio-crds.sh

      - name: Wait for Istio Pods Ready
        run: kubectl wait --for=condition=Ready pods --all -n istio-system --timeout=300s

      - name: 07 - Install Kiali
        run: |
          bash ./bin/07-kiali.sh

      - name: Install Gateway CRDs and Validate Gateway CRDs
        run: |
          bash scenarios/00-prerequisites/install-gateway-api-crds.sh
          bash scenarios/00-prerequisites/validate-gateway-api-crds.sh

      - name: Validate all Pods Ready
        run: |
          for ns in istio-system cattle-system monitoring; do
            echo "Waiting for pods in namespace $ns..."
            kubectl wait --for=condition=Ready pods --all -n $ns --timeout=300s || true
          done
          
          NOT_READY=$(kubectl get pods --all-namespaces --no-headers | awk '$4 != "Running" && $4 != "Completed" {print $0}')
          if [ -n "$NOT_READY" ]; then
              echo "Error: Some pods are not ready!"
              echo "$NOT_READY"
              exit 1
          fi

          echo "All pods are running."

      - name: Shutdown K8s Cluster
        run: |
          chmod +x ./bin/shutdown.sh
          ./bin/shutdown.sh
